# Generated by Django 3.2.6 on 2021-08-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_todo_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='completed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
